### ISSUE TITLE
Config-File Based Error: `ValueError: 'docs\\img\\rich-codex.yml' is not in the subpath` on Windows System

### ISSUE THREAD

**Issue by engineerjoe440** [ewels/rich-codex#26]
Hi there! Way cool project (and my props for it!), I want to use this all over the place.

I'm running into an issue on Windows (and that may very well be why, but I'm still just getting my sea-legs under me).

When I use a config file (still using *.rst for my Sphinx-docs, and have a bunch of automation around that, already - need to move to markdown, but haven't done it yet) in a repository configured as follows:

```
root
  |- docs/
  |    |- img/
  |    |    |- rich-codex.yml
  |    |
  |    | ...
  |
  | ...
```

The `rich-codex.yml` file contains the following:
```yaml
# Rich-Codex Configuration
# See More:
# https://ewels.github.io/rich-codex/inputs/config_file/

outputs:
  - command: "git-test help"
    img_paths:
      - docs/img/git-test-help.svg
```

> *mind you, `git-test` is a placeholder for special command that I have installed on my system*

When I run the `rich-codex` command from the root of my repository, I see a Python traceback as:

```python-traceback
$> rich-codex --skip-git-checks
INFO     rich-codex ⚡️📖⚡️ version 1.2.0
INFO     Trimming terminal output down to a minimum of 80
INFO     Found 1 config file
Traceback (most recent call last):
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\Scripts\rich-codex.exe\__main__.py", line 7, in <module>
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\rich_click\rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\rich_codex\cli.py", line 453, in main
    codex_obj.confirm_commands()
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\site-packages\rich_codex\codex_search.py", line 360, in confirm_commands
    rel_source = Path(img_obj.source).relative_to(Path.cwd())
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 928, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'docs\\img\\rich-codex.yml' is not in the subpath of 'C:\\Users\\joestan\\Documents\\test\\test-python\\docs\\img' OR one path is relative and the other is absolute.
```

I'm curious what I'm missing from my config, or if you have ideas of what might be going on. If this is a "bug" then I'd be happy to contribute, I just don't know enough (yet) to be sure if it's a problem or a PEBKAC issue.

**Comment by engineerjoe440** [comment]
Perhaps I should also add that I'm running the command-line instance tooling - that may have been clear from the traceback, but I wanted to be doubly sure!

**Comment by ewels** [comment]
Hmm, hopefully this is a bug and a fairly easy one to solve at that. I guess if we add a couple of `.absolute()` calls onto the two `Path` objects here, it'll work:

https://github.com/ewels/rich-codex/blob/c8f2b4b25e3f2de56307fc4f3432ad7945483aee/src/rich_codex/codex_search.py#L360

I suspect that I've gotten away with this so far because of either unix (I use a mac) or because of the way that I've been running the commands.

If you're able to try that and stick in a PR if it fixes the issue, that would be fab!

**Comment by ewels** [comment]
ps. I'm on holiday at the moment but can have a look next week if you have any issues.

**Comment by ewels** [comment]
Also, should probably add in a `try` / `except` block there to catch these errors and just print the uglier full path. I think that even in a perfect world, if you run the command on some files on a different file system (eg. a different disk on windows) then it will fail.

This 'relative to' function call is only for making the log easier to read, so should be no issue to fall back to the absolute path.

**Comment by ewels** [comment]
Managed to replicate locally with your example (thanks for that, super helpful!) and fixed. Just pushed a new release (v.1.2.1) which should solve the issue.

Thanks for reporting this! Let me know how you get on.

**Comment by engineerjoe440** [comment]
My goodness! Thank you @ewels! This is awesome work; and while you're on holiday, no less!

I'll give it a run today and report back. Thank you!

**Comment by engineerjoe440** [comment]
Marvelous!!! Looks like we've got past that one!
![image](https://user-images.githubusercontent.com/33275230/184672987-d14d5b01-a892-4211-973f-085b9532926e.png)


I think I'm still running into some issues, but they're undoubtedly related to some Windows nonsense. Let me go and better understand what's happening now. In the meantime - I can confirm that this issue is resolved. Thank you again!!!!
