### ISSUE TITLE
Video and/or gif Support

### ISSUE THREAD

**Issue by BrutalSimplicity** [ewels/rich-codex#41]
This is awesome work! Thank you for this and the `rich-click` integration. They are wonderful tools!

I think it would be great if `rich-codex` could also create gifs. I'm not sure if this is something supported by `rich` or possible through other means, but it would be neat to also have that option for longer commands, or more complex workflows with multiple commands.

**Comment by ewels** [comment]
Just saw this on the GitHub Twitter feed - looks pretty awesome! Might be the kind of thing you're looking for?

https://github.com/charmbracelet/vhs

**Comment by BrutalSimplicity** [comment]
That might be just what I need. Will try it out. Thanks for sharing.

**Comment by ewels** [comment]
ok I've just been playing with it and it's super nice 😍 

Might look into whether I can get rich-codex to have the option to call `vhs` to make these gifs.. Would be nice to be able to have both options and have the integrated markdown instructions still..

https://github.com/ewels/rich-codex/issues/42
