### ISSUE TITLE
Configuration to Display Similar to Windows Terminal?

### ISSUE THREAD

**Issue by engineerjoe440** [ewels/rich-codex#43]
This is a bit of an off-topic question, but I'm curious if you have suggestions for how I might be able to configure rich-codex to generate images that appear more similar to Windows' new terminal app?

![image](https://user-images.githubusercontent.com/33275230/207445690-591c246c-ada2-4f48-afbc-4e74ee8fc6dc.png)

Not exactly the most "elegant" view, but this would be very helpful for me when documenting Windows-based command-line tools. Is this something that's already supported, or if not, do you have suggestions on how it might be added? Maybe it's something that I could contribute? Assuming it's not too far beyond my skills.

**Comment by ewels** [comment]
This would be cool! The SVGs in rich-codex are generated by [rich](https://github.com/Textualize/rich) (see [docs](https://rich.readthedocs.io/en/latest/console.html#exporting-svgs)), so this is something that would need to go in upstream there ideally.

I guess we could add some code in rich-codex to edit the generated SVGs and bring in the different frame in post-processing, but I suspect it would not be trivial.. As such, I'm afraid I don't see this happening any time soon.

**Comment by ewels** [comment]
Closing for now, can reopen if you think that there's more to do here 👍🏻

**Comment by engineerjoe440** [comment]
Thanks, @ewels! I'd meant to respond and thank you for your thoughts and feedback. This is perfect, and much appreciated!

Hopefully I'll be able to poke around there at some point soon!
